#!/usr/bin/env tsx
/**
 * Build-time scraper. Pulls every provider settings doc from
 * docs.postiz.com/public-api/providers/{name}.md, extracts the canonical
 * JSON example as `defaultSettings`, and emits src/providers/schemas.ts
 * as a typed bundle. Run on demand (npm run refresh-schemas) or via the
 * monthly GitHub Action.
 *
 * The output is checked in. The MCP server reads it directly - no fetch at
 * runtime, no docs.postiz.com dependency in the install path.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

/** Providers Postiz has published a public-API doc for. These MUST fetch
 *  successfully or the bundle refresh fails. Drift here means docs.postiz.com
 *  changed something we depend on. */
const DOCUMENTED_PROVIDERS: string[] = [
  "bluesky",
  "devto",
  "discord",
  "dribbble",
  "facebook",
  "gmb",
  "hashnode",
  "instagram",
  "instagram-standalone",
  "kick",
  "lemmy",
  "linkedin",
  "linkedin-page",
  "listmonk",
  "mastodon",
  "medium",
  "moltbook",
  "nostr",
  "pinterest",
  "reddit",
  "skool",
  "slack",
  "telegram",
  "threads",
  "tiktok",
  "twitch",
  "vk",
  "warpcast",
  "whop",
  "wordpress",
  "x",
  "youtube",
];

/** Real Postiz providers (source files exist in postiz-app) that have never
 *  had a public-api doc. We fetch opportunistically: a 404 is expected and
 *  ignored, but a 200 means upstream just published the doc - log loudly so
 *  the next cron PR moves the slug into DOCUMENTED_PROVIDERS. */
const UNDOCUMENTED_PROVIDERS: string[] = [
  "mastodon-custom",
  "mewe",
];

const ALL_PROVIDERS = new Set([...DOCUMENTED_PROVIDERS, ...UNDOCUMENTED_PROVIDERS]);

interface ProviderRecord {
  slug: string;
  type: string;
  sourceUrl: string;
  fetchedAt: string;
  defaultSettings: Record<string, unknown> | null;
  markdown: string;
}

async function fetchProvider(slug: string): Promise<ProviderRecord> {
  const sourceUrl = `https://docs.postiz.com/public-api/providers/${slug}.md`;
  const res = await fetch(sourceUrl);
  if (!res.ok) {
    throw new Error(`fetch ${sourceUrl} -> HTTP ${res.status}`);
  }
  const markdown = sanitizeMarkdown(await res.text());
  const defaultSettings = extractFirstSettingsBlock(markdown);
  const type =
    defaultSettings && typeof defaultSettings.__type === "string"
      ? defaultSettings.__type
      : slug;
  return {
    slug,
    type,
    sourceUrl,
    fetchedAt: new Date().toISOString(),
    defaultSettings,
    markdown,
  };
}

/** Find the first json/jsonc fenced block whose parsed body has a top-level
 *  `settings` object - that's the canonical "Settings Schema" example. Falls
 *  back to the first JSON block whose body itself looks like a settings
 *  object (has __type), since some provider docs put the settings inline
 *  without wrapping in `{settings: ...}`. Tolerates `~~~` fences and
 *  case-insensitive language tags so a single docs-formatting tweak doesn't
 *  silently empty the bundle. */
function extractFirstSettingsBlock(md: string): Record<string, unknown> | null {
  const fenceRe = /(?:```|~~~)\s*(?:json|jsonc)\b[^\n]*\n([\s\S]*?)\n(?:```|~~~)/gi;
  let match: RegExpExecArray | null;
  let firstWithType: Record<string, unknown> | null = null;
  while ((match = fenceRe.exec(md))) {
    const body = match[1];
    let parsed: unknown;
    try {
      parsed = JSON.parse(body);
    } catch {
      continue;
    }
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      const obj = parsed as Record<string, unknown>;
      if (obj.settings && typeof obj.settings === "object") {
        return obj.settings as Record<string, unknown>;
      }
      if (typeof obj.__type === "string" && firstWithType === null) {
        firstWithType = obj;
      }
    }
  }
  return firstWithType;
}

/** Replace upstream em dashes with hyphens at ingest so the bundled
 *  provider markdown stays compliant with the no-em-dash rule even when
 *  docs.postiz.com uses them. */
function sanitizeMarkdown(md: string): string {
  return md.replace(/—/g, "-").replace(/–/g, "-");
}

function toModule(records: ProviderRecord[]): string {
  const sorted = [...records].sort((a, b) => a.slug.localeCompare(b.slug));
  const data = JSON.stringify(sorted, null, 2);
  return `// AUTO-GENERATED by scripts/fetch-provider-schemas.ts. DO NOT EDIT BY HAND.
// Run \`npm run refresh-schemas\` to update.
//
// Source: https://docs.postiz.com/public-api/providers/{slug}.md
// Generated: ${new Date().toISOString()}

export interface ProviderSchema {
  /** URL slug used by docs.postiz.com (e.g. "x", "gmb"). */
  slug: string;
  /** Value for the \`__type\` field inside the \`settings\` block. Usually
   *  matches \`slug\` but not always. */
  type: string;
  /** Canonical URL the markdown was scraped from. */
  sourceUrl: string;
  /** ISO-8601 timestamp of the last successful scrape. */
  fetchedAt: string;
  /** First settings example parsed from the doc, or null if extraction
   *  failed. Use as a starting template, not a strict schema. */
  defaultSettings: Record<string, unknown> | null;
  /** Full markdown body of the provider doc, including field tables and
   *  worked examples. Returned verbatim by \`get_provider_settings_schema\`
   *  so an LLM caller has everything it needs to construct valid payloads. */
  markdown: string;
}

export const PROVIDER_SCHEMAS: ProviderSchema[] = ${data};

export const PROVIDER_SCHEMA_BY_SLUG: Record<string, ProviderSchema> =
  Object.freeze(
    PROVIDER_SCHEMAS.reduce<Record<string, ProviderSchema>>((acc, p) => {
      acc[p.slug] = p;
      return acc;
    }, {}),
  );

export const PROVIDER_SCHEMA_BY_TYPE: Record<string, ProviderSchema> =
  Object.freeze(
    PROVIDER_SCHEMAS.reduce<Record<string, ProviderSchema>>((acc, p) => {
      acc[p.type] = p;
      return acc;
    }, {}),
  );

export const PROVIDER_SLUGS = PROVIDER_SCHEMAS.map((p) => p.slug);
`;
}

/** Sanity-check thresholds. If any of these trip, we exit non-zero rather
 *  than write a degraded bundle. The previous behaviour (write anything
 *  non-empty, log errors, exit 0) silently dropped providers and broke
 *  postiz_get_provider_settings_schema for them on the next run. */
const MIN_FETCH_SUCCESS_RATIO = 0.9;
const MAX_NULL_SETTINGS_RATIO = 0.25;

async function main(): Promise<void> {
  const records: ProviderRecord[] = [];
  const documentedFailures: string[] = [];
  const newlyDocumented: string[] = [];

  for (const slug of DOCUMENTED_PROVIDERS) {
    try {
      const r = await fetchProvider(slug);
      records.push(r);
      const status = r.defaultSettings ? "ok" : "no-json-block";
      console.log(`  ${slug.padEnd(20)} ${status}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      documentedFailures.push(`${slug}: ${msg}`);
      console.error(`  ${slug.padEnd(20)} FAILED ${msg}`);
    }
  }

  for (const slug of UNDOCUMENTED_PROVIDERS) {
    try {
      const r = await fetchProvider(slug);
      records.push(r);
      newlyDocumented.push(slug);
      const status = r.defaultSettings ? "ok" : "no-json-block";
      console.log(`  ${slug.padEnd(20)} ${status} (newly documented)`);
    } catch {
      console.log(`  ${slug.padEnd(20)} skipped (no upstream doc, expected)`);
    }
  }

  if (newlyDocumented.length > 0) {
    console.log(
      `\nNEW: ${newlyDocumented.length} previously-undocumented provider(s) now have docs: ` +
        `${newlyDocumented.join(", ")}.\n` +
        `Move them from UNDOCUMENTED_PROVIDERS to DOCUMENTED_PROVIDERS in scripts/fetch-provider-schemas.ts.`,
    );
  }

  const documentedFetched = DOCUMENTED_PROVIDERS.length - documentedFailures.length;
  const successRatio = documentedFetched / DOCUMENTED_PROVIDERS.length;
  if (successRatio < MIN_FETCH_SUCCESS_RATIO) {
    console.error(
      `Only ${documentedFetched}/${DOCUMENTED_PROVIDERS.length} documented provider docs fetched ` +
        `(${(successRatio * 100).toFixed(1)}% < ${MIN_FETCH_SUCCESS_RATIO * 100}% floor). ` +
        `Refusing to overwrite the bundled schemas.`,
    );
    process.exit(1);
  }
  const nullCount = records.filter((r) => r.defaultSettings === null).length;
  const nullRatio = records.length === 0 ? 0 : nullCount / records.length;
  if (nullRatio > MAX_NULL_SETTINGS_RATIO) {
    console.error(
      `${nullCount}/${records.length} fetched providers had no parseable JSON block ` +
        `(${(nullRatio * 100).toFixed(1)}% > ${MAX_NULL_SETTINGS_RATIO * 100}% ceiling). ` +
        `The fence regex or docs format likely changed; refusing to overwrite.`,
    );
    process.exit(1);
  }

  // Merge over the existing bundle: a per-provider fetch failure preserves
  // the previously-bundled record (with a `staleSince` marker) instead of
  // silently dropping the provider from the bundle.
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const outPath = join(__dirname, "..", "src", "providers", "schemas.ts");
  const fetchedSlugs = new Set(records.map((r) => r.slug));
  const stalePreserved: ProviderRecord[] = [];
  if (existsSync(outPath)) {
    const existing = readExistingBundle(outPath);
    for (const prev of existing) {
      if (fetchedSlugs.has(prev.slug)) continue;
      if (!ALL_PROVIDERS.has(prev.slug)) continue;
      stalePreserved.push({
        ...prev,
        markdown: sanitizeMarkdown(prev.markdown),
      });
    }
  }
  const merged = [...records, ...stalePreserved];
  writeFileSync(outPath, toModule(merged));
  console.log(
    `\nWrote ${merged.length} provider schema records to ${outPath}` +
      (documentedFailures.length
        ? ` (${documentedFailures.length} documented fetch(es) failed, ${stalePreserved.length} preserved from prior bundle)`
        : ""),
  );
}

/** Best-effort parse of the previous schemas.ts. Returns [] if anything
 *  about the format has drifted; the caller treats that as "no prior bundle
 *  to preserve from" and proceeds with just the freshly-fetched records. */
function readExistingBundle(path: string): ProviderRecord[] {
  try {
    const src = readFileSync(path, "utf-8");
    const m = src.match(/PROVIDER_SCHEMAS:\s*ProviderSchema\[\]\s*=\s*(\[[\s\S]*?\]);\s*\n/);
    if (!m) return [];
    const parsed = JSON.parse(m[1]) as unknown;
    if (!Array.isArray(parsed)) return [];
    return parsed as ProviderRecord[];
  } catch {
    return [];
  }
}

main().catch((err) => {
  console.error(`fetch-provider-schemas fatal: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
