#!/usr/bin/env tsx
/**
 * Build-time scraper. Pulls every provider settings doc from
 * docs.postiz.com/public-api/providers/{name}.md, extracts the canonical
 * JSON example as `defaultSettings`, and emits src/providers/schemas.ts
 * as a typed bundle. Run on demand (npm run refresh-schemas) or via the
 * monthly GitHub Action.
 *
 * The output is checked in. The MCP server reads it directly — no fetch at
 * runtime, no docs.postiz.com dependency in the install path.
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const PROVIDERS: string[] = [
  "devto",
  "discord",
  "dribbble",
  "facebook",
  "gmb",
  "hashnode",
  "instagram",
  "kick",
  "lemmy",
  "linkedin",
  "listmonk",
  "medium",
  "moltbook",
  "pinterest",
  "reddit",
  "skool",
  "slack",
  "tiktok",
  "twitch",
  "warpcast",
  "whop",
  "wordpress",
  "x",
  "youtube",
];

interface ProviderRecord {
  slug: string;
  type: string;
  sourceUrl: string;
  fetchedAt: string;
  defaultSettings: Record<string, unknown> | null;
  markdown: string;
}

async function fetchProvider(slug: string): Promise<ProviderRecord> {
  const sourceUrl = `https://docs.postiz.com/public-api/providers/${slug}.md`;
  const res = await fetch(sourceUrl);
  if (!res.ok) {
    throw new Error(`fetch ${sourceUrl} → HTTP ${res.status}`);
  }
  const markdown = await res.text();
  const defaultSettings = extractFirstSettingsBlock(markdown);
  const type =
    (defaultSettings && typeof defaultSettings.__type === "string"
      ? defaultSettings.__type
      : slug);
  return {
    slug,
    type,
    sourceUrl,
    fetchedAt: new Date().toISOString(),
    defaultSettings,
    markdown,
  };
}

/** Find the first ```json fenced block whose parsed body has a top-level
 *  `settings` object — that's the canonical "Settings Schema" example. Falls
 *  back to the first JSON block whose body itself looks like a settings
 *  object (has __type), since some provider docs put the settings inline
 *  without wrapping in `{settings: ...}`. */
function extractFirstSettingsBlock(md: string): Record<string, unknown> | null {
  const fenceRe = /```json[^\n]*\n([\s\S]*?)\n```/g;
  let match: RegExpExecArray | null;
  let firstWithType: Record<string, unknown> | null = null;
  while ((match = fenceRe.exec(md))) {
    const body = match[1];
    let parsed: unknown;
    try {
      parsed = JSON.parse(body);
    } catch {
      continue;
    }
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      const obj = parsed as Record<string, unknown>;
      if (obj.settings && typeof obj.settings === "object") {
        return obj.settings as Record<string, unknown>;
      }
      if (typeof obj.__type === "string" && firstWithType === null) {
        firstWithType = obj;
      }
    }
  }
  return firstWithType;
}

function toModule(records: ProviderRecord[]): string {
  const sorted = [...records].sort((a, b) => a.slug.localeCompare(b.slug));
  const data = JSON.stringify(sorted, null, 2);
  return `// AUTO-GENERATED by scripts/fetch-provider-schemas.ts. DO NOT EDIT BY HAND.
// Run \`npm run refresh-schemas\` to update.
//
// Source: https://docs.postiz.com/public-api/providers/{slug}.md
// Generated: ${new Date().toISOString()}

export interface ProviderSchema {
  /** URL slug used by docs.postiz.com (e.g. "x", "gmb"). */
  slug: string;
  /** Value for the \`__type\` field inside the \`settings\` block. Usually
   *  matches \`slug\` but not always. */
  type: string;
  /** Canonical URL the markdown was scraped from. */
  sourceUrl: string;
  /** ISO-8601 timestamp of the last successful scrape. */
  fetchedAt: string;
  /** First settings example parsed from the doc, or null if extraction
   *  failed. Use as a starting template, not a strict schema. */
  defaultSettings: Record<string, unknown> | null;
  /** Full markdown body of the provider doc, including field tables and
   *  worked examples. Returned verbatim by \`get_provider_settings_schema\`
   *  so an LLM caller has everything it needs to construct valid payloads. */
  markdown: string;
}

export const PROVIDER_SCHEMAS: ProviderSchema[] = ${data};

export const PROVIDER_SCHEMA_BY_SLUG: Record<string, ProviderSchema> =
  Object.freeze(
    PROVIDER_SCHEMAS.reduce<Record<string, ProviderSchema>>((acc, p) => {
      acc[p.slug] = p;
      return acc;
    }, {}),
  );

export const PROVIDER_SCHEMA_BY_TYPE: Record<string, ProviderSchema> =
  Object.freeze(
    PROVIDER_SCHEMAS.reduce<Record<string, ProviderSchema>>((acc, p) => {
      acc[p.type] = p;
      return acc;
    }, {}),
  );

export const PROVIDER_SLUGS = PROVIDER_SCHEMAS.map((p) => p.slug);
`;
}

async function main(): Promise<void> {
  const records: ProviderRecord[] = [];
  const errors: string[] = [];
  for (const slug of PROVIDERS) {
    try {
      const r = await fetchProvider(slug);
      records.push(r);
      const status = r.defaultSettings ? "ok" : "no-json-block";
      console.log(`  ${slug.padEnd(12)} ${status}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`${slug}: ${msg}`);
      console.error(`  ${slug.padEnd(12)} FAILED ${msg}`);
    }
  }
  if (records.length === 0) {
    console.error("All provider fetches failed; refusing to overwrite schemas.");
    process.exit(1);
  }
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const outPath = join(__dirname, "..", "src", "providers", "schemas.ts");
  writeFileSync(outPath, toModule(records));
  console.log(
    `\nWrote ${records.length} provider schema records to ${outPath}` +
      (errors.length ? ` (${errors.length} failed)` : ""),
  );
}

main().catch((err) => {
  console.error(`fetch-provider-schemas fatal: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
